# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_auto_20160806_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
